### ISSUE TITLE
Update to 1.21?

### ISSUE THREAD

**Issue by Quackdd** [FlamedDogo99/AmethystArmor#1]
This isn't necessarily an issue with your code and I haven't tested anything for 1.21, but I wanted to add a sword with custom attributes like you did and couldn't find anything anywhere on the internet. I ended up copying your code with changing several of the numerical values and lo and behold, it didn't work. The recipe doesn't show up with an output and I get a "No key id in MapLike" error in a server console twice and a "missed input:" error once. It's definitely an issue with the attribute system perhaps with updating to 1.21 but I was wondering if you knew anything about it. Thanks!
![image_2024-07-16_224034070](https://github.com/user-attachments/assets/e5efb7c3-e6df-4bfc-b91c-2f55689cbc53)
![image_2024-07-16_224240234](https://github.com/user-attachments/assets/10edbf31-d6a8-4744-b62b-e4173014d8fc)

**Comment by Quackdd** [comment]
I got it working! Sorry for bothering you I got hopeless for a second. 
The old UUID system had been replaced by just "id": ""

**Comment by FlamedDogo99** [comment]
I somehow forgot that 1.21 had dropped already. I just updated the datapack and resource pack to the newest version, sorry about that.
